- name: Install and configure Docker
  hosts: app
  become: yes
  
  tasks:
    - name: Install Docker
      include_role:
        name: Docker

- name: Install and configure Nginx
  hosts: web
  become: yes
  
  tasks:
    - name: Install Nginx
      include_role:
        name: nginx

- import_playbook: playbooks/local/clone_repo.yml
- import_playbook: playbooks/local/run_app.yml
